function createfigure(X1, Y1, S1, C1, Y2, C2, Y3, C3, Y4, C4)
%CREATEFIGURE(X1, Y1, S1, C1, Y2, C2, Y3, C3, Y4, C4)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c
%  Y2:  scatter y
%  C2:  scatter c
%  Y3:  scatter y
%  C3:  scatter c
%  Y4:  scatter y
%  C4:  scatter c

%  Auto-generated by MATLAB on 04-Dec-2018 14:43:24

% Create figure
figure;

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,S1,C1,'DisplayName','R_b','MarkerFaceColor',[1 1 1],...
    'MarkerEdgeColor',[0 0.447058826684952 0.74117648601532]);

% Create scatter
scatter(X1,Y2,S1,C2,'DisplayName','L_e','MarkerFaceColor',[1 1 1],...
    'MarkerEdgeColor',[1 0 0]);

% Create scatter
scatter(X1,Y3,S1,C3,'DisplayName','R_m','MarkerFaceColor',[1 1 1],...
    'MarkerEdgeColor',[0 1 0]);

% Create scatter
scatter(X1,Y4,S1,C4,'DisplayName','L_r','MarkerFaceColor',[1 1 1]);

% Create xlabel
xlabel('Fitness Value [mm^3]','FontSize',11);

% Create ylabel
ylabel('Solutions [mm]','FontSize',11);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[15000000 240000000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-50 1000]);
view(axes1,[0.800000000000011 90]);
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northeast');

